// src/shared/components/common/button/index.tsx
import { cva, VariantProps } from "class-variance-authority";
import { forwardRef, HTMLAttributes } from "react";

const button = cva("font-medium flex items-center", {
  variants: {
    intent: {
      filled: ["bg-primary-90 text-default-white hover:bg-primary-60"],
      outlined: ["bg-default-white text-primary-90 border border-gray-30"],
      danger: ["bg-default-allert text-default-white"],
      disabled: ["bg-gray-30 text-default-white"],
      link: ["text-primary-90 hover:underline decoration-primary-90"],
    },
    size: {
      large: ["px-8 text-xl h-14"],
      medium: ["px-7 h-12"],
      small: ["px-7 text-sm h-10"],
    },
  },
  defaultVariants: {
    intent: "filled",
    size: "medium",
  },
});

type IButtonType = "button" | "submit" | undefined;

interface IButtonProps
  extends HTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof button> {
  type?: IButtonType;
}

export const Button = forwardRef<HTMLButtonElement, IButtonProps>(
  ({ className, intent, size, ...rest }, ref) => (
    <button
      ref={ref}
      className={button({ className, intent, size })}
      {...rest}
    />
  )
);

// src/app/shared/components/common/button/button.component.ts
import { IButtonType } from '@/app/shared/components/common/button/interface';
import { NgIf } from '@angular/common';
import {
  Component,
  EventEmitter,
  Host,
  HostBinding,
  Input,
  Output,
} from '@angular/core';
import { cva, type VariantProps } from 'class-variance-authority';

type ButtonVariants = VariantProps<typeof button>;

const button = cva(['font-medium block w-fit align-middle'], {
  variants: {
    intent: {
      filled: 'text-default-white bg-primary-90 hover:bg-primary-60',
      outline: 'border border-gray-30 bg-default-white text-primary-90',
      danger: 'bg-default-alert text-default-white',
      link: 'hover:underline text-primary-90 decoration-primary-90',
    },
    size: {
      large: 'text-[20px] h-14',
      medium: 'h-12 text-base',
      small: 'text-sm h-10',
    },
  },
  defaultVariants: {
    intent: 'filled',
    size: 'large',
  },
});

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [NgIf],
  templateUrl: './button.component.html',
  styleUrl: './button.component.css',
})
export class ButtonComponent {
  @Input() class: string | undefined;
  @Input() disabled: boolean | undefined;
  @Input() variant: ButtonVariants['intent'];
  @Input() size: ButtonVariants['size'];
  @Input() srartIcon: string | undefined;
  @Input() endIcon: string | undefined;
  @Input() type: IButtonType;
  @Output() handleClick = new EventEmitter<MouseEvent>();

  onClickButton(event: MouseEvent) {
    this.handleClick.emit(event);
  }

  @HostBinding('class')
  get _getButtonVarinats() {
    return button({ size: this.size, intent: this.variant });
  }
}

<button
  (click)="onClickButton($event)"
  class="h-full w-full px-4"
  [type]="type"
>
  <div class="flex items-center gap-3">
    <i [class]="srartIcon" class="text-2xl" *ngIf="srartIcon"></i>
    <ng-content />
    <i [class]="endIcon" class="text-2xl" *ngIf="endIcon"></i>
  </div>
</button>
