// src/app/shared/components/avatar/avatar.component.ts
import { NgIf } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-avatar',
  standalone: true,
  imports: [NgIf],
  templateUrl: './avatar.component.html',
  styleUrl: './avatar.component.css',
})
export class AvatarComponent {
  @Input() src: string | undefined;
}

<div class="w-10 h-10 rounded-full bg-gray-10 flex items-center justify-center">
  <img src="/assets/images/avatar.svg" />
</div>

// src/shared/components/avatar/index.tsx
import user from "@shared/assets/icons/user.svg";

interface IAvatarProps {
  src?: string;
  width?: number;
  height?: number;
}

export const Avatar = ({ src, width, height }: IAvatarProps) => {
  return (
    <div
      className="flex justify-center items-center w-[48px] h-[48px] bg-gray-10 rounded-full bg-cover"
      style={{ backgroundImage: `url(${src})`, width: width, height: height }}
    >
      {!src && <img src={user} />}
    </div>
  );
};
