// src/widgets/header/index.tsx
import logo from "@shared/assets/icons/logo.svg";
import { Tabs } from "@shared/components/common/tabs";
import { ERoutes } from "@shared/enums/routes";

export const Header = () => {
  return (
    <header className="py-4 px-6 border-b border border-gray-20">
      <section className="flex gap-12 items-center">
        <img src={logo} />
        <Tabs
          options={[
            { label: "Сотрудники", to: ERoutes.EMPLOYEES },
            { label: "Мероприятия", to: ERoutes.EVENTS },
          ]}
        />
      </section>
    </header>
  );
};

// src/app/widgets/header/header.component.ts
import { TabComponent } from '@/app/shared/components/common/tab/tab.component';
import { TabsComponent } from '@/app/shared/components/common/tabs/tabs.component';
import { ERoutes } from '@/app/shared/enums/routes';
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [TabComponent, TabsComponent],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent {
  employeesRoute = ERoutes.employees;
  eventsRoute = ERoutes.events;
}

<div class="py-4 px-6 flex gap-12">
  <section
    class="w-[220px] h-[30px] bg-primary-60 border-b border-gray-20"
  ></section>
  <app-tabs>
    <app-tab [to]="employeesRoute">Сотрудники</app-tab>
    <app-tab [to]="eventsRoute">Мероприятия</app-tab>
  </app-tabs>
</div>
